export interface Tag {
  value: string;
  type: TAG_TYPE;
}

export enum TAG_TYPE {
  LOCATION = "LOCATION",
  COMPANY = "COMPANY",
  PROGRAMMING_LANGUAGE = "PROGRAMMING_LANGUAGE",
  FRAMEWORK = "FRAMEWORK",
  TECHNOLOGY = "TECHNOLOGY",
  PLATFORM = "PLATFORM"
}