export interface Tag {
	value: string;
	type: TAG_TYPE;
}

export enum TAG_TYPE {
	PROGRAMMING_LANGUAGE = "PROGRAMMING_LANGUAGE",
	FRAMEWORK = "FRAMEWORK",
	TECHNOLOGY = "TECHNOLOGY",
	PLATFORM = "PLATFORM"
}